common/models/TenantRab.php
<?php

namespace common\models;

use Yii;
use yii\helpers\Url;
use yii\web\UploadedFile;
/**
 * This is the model class for table "tenant_rab".
 *
 * @property int $id
 * @property int $id_kegiatan
 * @property double $jumlah
 * @property string $upload_rab
 *
 * @property TenantKegiatan $kegiatan
 */
class TenantRab extends \yii\db\ActiveRecord
{
    public $rab;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tenant_rab';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_kegiatan', 'jumlah', 'upload_rab'], 'required'],
            [['id_kegiatan'], 'integer'],
            [['jumlah'], 'number'],
            [['upload_rab'], 'string', 'max' => 200],
            [['id_kegiatan'], 'exist', 'skipOnError' => true, 'targetClass' => TenantKegiatan::className(), 'targetAttribute' => ['id_kegiatan' => 'id']],
            [['rab'], 'file', 'extensions' => 'jpg, jpeg, png'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_kegiatan' => 'Id Kegiatan',
            'jumlah' => 'Jumlah',
            'upload_rab' => 'Upload Rab',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKegiatan()
    {
        return $this->hasOne(TenantKegiatan::className(), ['id' => 'id_kegiatan']);
    }

    public function getUploadRab()
    {
        return \Yii::$app->params['backendImagesUrl'].'/rab/'.$this->upload_rab;
    }

    public function getUploadRabUrl()
    {
        return $this->upload_rab ? Url::to('@web/images/rab/'.$this->upload_rab) : '';
    }
}

backend/controllers/TenantRabController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\TenantRab;
use backend\models\TenantRabSearch;
use common\models\TenantKegiatan;
use backend\models\TenantKegiatanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * TenantRabController implements the CRUD actions for TenantRab model.
 */
class TenantRabController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TenantRab models.
     * @return mixed
     */
    public function actionRab()
    {
        $this->layout = 'admin';
        $searchModel = new TenantRabSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('rab', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndex()
    {
        $this->layout = 'admin';
        $searchModel = new TenantKegiatanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('Index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TenantRab model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $this->layout = 'admin';
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TenantRab model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = 'admin';
        $model = new TenantRab();
        Yii::$app->params['uploadPath']= Yii::$app->basePath . '/web/images/rab/';

        if ($model->load(Yii::$app->request->post())) {
            $img = UploadedFile::getInstance($model, 'rab');
            $model->upload_rab = $img->name;
            $model->rab = $img;
            $model->save();
            $model->rab->saveAs(Yii::$app->params['uploadPath'] . $model->rab);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing TenantRab model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $this->layout = 'admin';
        $model = $this->findModel($id);
        Yii::$app->params['uploadPath']= Yii::$app->basePath . '/web/images/rab/';

        if ($model->load(Yii::$app->request->post())) {
            $img = UploadedFile::getInstance($model, 'rab');
            $model->upload_rab = $img->name;
            $model->rab = $img;
            $model->save();
            $model->rab->saveAs(Yii::$app->params['uploadPath'] . $model->rab);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing TenantRab model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->layout = 'admin';
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TenantRab model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TenantRab the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TenantRab::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/tenant-rab/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;
use yii\helpers\ArrayHelper;
use common\models\TenantKegiatan;

/* @var $this yii\web\View */
/* @var $model common\models\TenantRab */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Daftar RAB Tenant
                    </h3>
                </div>
                <div class="panel-body" >
					<div class="tenant-rab-form">

					    <?php $form = ActiveForm::begin(); ?>

                        <?php \Yii::$app->request->get('id_kegiatan') ? $model->id_kegiatan = \Yii::$app->request->get('id_kegiatan') : '' ?>
                        <?= $form->field($model, 'id_kegiatan')->hiddenInput()->label(false) ?>

                        <?php
                        // $form->field($model, 'id_kegiatan')->widget(Select2::classname(), [
                        //     'data' => ArrayHelper::map(TenantKegiatan::find()->isSelf()->orderBy('nama_kegiatan')->asArray()->all(), 'id', 'nama_kegiatan'),
                        //     'disabled' => true,
                        //     'options' => [
                        //         // 'disabled' => (! Yii::$app->user->can('Penelitian Pengajuan All')),
                        //         'placeholder' => 'Pilih Nama Nama Kegiatan ...',
                        //     ],
                        //     'pluginOptions' => [
                        //         'allowClear' => true,
                        //     ],
                        // ])
                        ?>

					    <?= $form->field($model, 'jumlah')->textInput() ?>

					    <?= $form->field($model, 'rab')->fileInput() ?>

					    <div class="form-group">
					        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
					    </div>

					    <?php ActiveForm::end(); ?>

					</div>
                </div>
                <div class="panel-footer">
                    Panel footer
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/tenant-rab/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\TenantRabSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Daftar RAB Tenant
                    </h3>
                </div>
                <div class="panel-body" >
                    <div class="tenant-rab-search">

                        <?php $form = ActiveForm::begin([
                            'action' => ['index'],
                            'method' => 'get',
                        ]); ?>

                        <?= $form->field($model, 'id') ?>

                        <?= $form->field($model, 'id_kegiatan') ?>

                        <?= $form->field($model, 'jumlah') ?>

                        <?= $form->field($model, 'upload_rab') ?>

                        <div class="form-group">
                            <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
                            <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
                        </div>

                        <?php ActiveForm::end(); ?>

                    </div>
                </div>
                <div class="panel-footer">
                    Panel footer
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/tenant-rab/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\TenantRab */

$this->title = 'Create Tenant Rab';
$this->params['breadcrumbs'][] = ['label' => 'Tenant Rabs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tenant-rab-create">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/tenant-rab/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\TenantKegiatanSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tenant RAB';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Daftar Tenant RAB
                    </h3>
                </div>
                <div class="panel-body" >
                    <div class="tenant-kegiatan-index">
                        <?= GridView::widget([
                            'dataProvider' => $dataProvider,
                            'filterModel' => $searchModel,
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn'],

                                // 'id',
                                'nama_kegiatan',
                                'koordinator_peneliti',
                                // 'judul',
                                // 'tujuan:raw',
                                //'sasaran:raw',
                                //'id_pic',

                                [
                                    'buttons' => [
                                        'view' => function ($url, $model, $key) {
                                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', Url::to(['/tenant-rab/rab', 'TenantRabSearch[id_kegiatan]' => $model->id]), ['title' => Yii::t('yii', 'View')]);
                                        },
                                    ],
                                    'class' => 'yii\grid\ActionColumn',
                                    'template' => '{view}'
                                ],
                            ],
                        ]); ?>
                    </div>
                </div>
                <div class="panel-footer">
                    Panel footer
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/tenant-rab/rab.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\TenantRabSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tenant Rabs';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Daftar RAB Tenant
                    </h3>
                </div>
                <div class="panel-body" >
                    <div class="tenant-rab-index">

                        <!-- <h1><?= Html::encode($this->title) ?></h1> -->
                        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

                        <p>
                            <?= Html::a('Create Tenant Rab', ['create', 'id_kegiatan' => \Yii::$app->request->get('TenantRabSearch')['id_kegiatan']], ['class' => 'btn btn-success']) ?>
                        </p>

                        <?= GridView::widget([
                            'dataProvider' => $dataProvider,
                            'filterModel' => $searchModel,
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn'],

                                // 'id',
                                // 'id_kegiatan',
                                'jumlah',
                                [
                                    'attribute' =>'upload_rab',
                                    'format' => 'raw',
                                    'value' => function ($row) {
                                        return $uploadRab = Html::img(
                                            $row->getUploadRabUrl(),
                                            ['style' => 'width:50px; heigth:20px;']
                                        );
                                    }
                                ],

                                ['class' => 'yii\grid\ActionColumn'],
                            ],
                        ]); ?>
                    </div>
                </div>
                <div class="panel-footer">
                    Panel footer
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/tenant-rab/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\TenantRab */

$this->title = 'Update Tenant Rab';
$this->params['breadcrumbs'][] = ['label' => 'Tenant Rabs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tenant-rab-update">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/tenant-rab/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\TenantRab */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Tenant Rabs', 'url' => ['rab', 'TenantRabSearch[id_kegiatan]' => $model->id_kegiatan]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Daftar RAB Tenant
                    </h3>
                </div>
                <div class="panel-body" >
                    <div class="tenant-rab-view">

                        <h1><?= Html::encode($this->title) ?></h1>

                        <p>
                            <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                                'class' => 'btn btn-danger',
                                'data' => [
                                    'confirm' => 'Are you sure you want to delete this item?',
                                    'method' => 'post',
                                ],
                            ]) ?>
                        </p>

                        <?= DetailView::widget([
                            'model' => $model,
                            'attributes' => [
                                'id',
                                'id_kegiatan',
                                'jumlah',
                                [
                                    'attribute' =>'upload_rab',
                                    'format' => 'raw',
                                    'value' => function ($row) {
                                        return $uploadRab = Html::img(
                                            $row->getUploadRabUrl(),
                                            ['style' => 'width:50px; heigth:20px;']
                                        );
                                    }
                                ],
                            ],
                        ]) ?>

                    </div>
                </div>
                <div class="panel-footer">
                    Panel footer
                </div>
            </div>
        </div>
    </div>
</div>