common/models/TenantLogbook.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "tenant_logbook".
 *
 * @property int $id
 * @property int $id_kegiatan
 * @property string $jenis_belanja
 * @property double $nominal
 * @property string $tanggal_pengajuan
 * @property string $tanggal_pencairan
 *
 * @property TenantKegiatan $kegiatan
 */
class TenantLogbook extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tenant_logbook';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_kegiatan', 'jenis_belanja', 'nominal', 'tanggal_pengajuan', 'tanggal_pencairan'], 'required'],
            [['id_kegiatan'], 'integer'],
            [['nominal'], 'number'],
            [['tanggal_pengajuan', 'tanggal_pencairan'], 'safe'],
            [['jenis_belanja'], 'string', 'max' => 300],
            [['id_kegiatan'], 'exist', 'skipOnError' => true, 'targetClass' => TenantKegiatan::className(), 'targetAttribute' => ['id_kegiatan' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_kegiatan' => 'Id Kegiatan',
            'jenis_belanja' => 'Jenis Belanja',
            'nominal' => 'Nominal',
            'tanggal_pengajuan' => 'Tanggal Pengajuan',
            'tanggal_pencairan' => 'Tanggal Pencairan',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKegiatan()
    {
        return $this->hasOne(TenantKegiatan::className(), ['id' => 'id_kegiatan']);
    }
}

backend/controllers/TenantLogbookController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\TenantLogbook;
use backend\models\TenantLogbookSearch;
use common\models\TenantKegiatan;
use backend\models\TenantKegiatanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TenantLogbookController implements the CRUD actions for TenantLogbook model.
 */
class TenantLogbookController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TenantLogbook models.
     * @return mixed
     */
    public function actionLogbook()
    {
        $this->layout = 'admin';
        $searchModel = new TenantLogbookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('logbook', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

     public function actionIndex()
    {
        $this->layout = 'admin';
        $searchModel = new TenantKegiatanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('Index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * Displays a single TenantLogbook model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $this->layout = 'admin';
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TenantLogbook model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = 'admin';
        $model = new TenantLogbook();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing TenantLogbook model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $this->layout = 'admin';
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing TenantLogbook model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->layout = 'admin';
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TenantLogbook model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TenantLogbook the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TenantLogbook::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/tenant-logbook/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;
use yii\helpers\ArrayHelper;
use common\models\TenantKegiatan;
use kartik\datecontrol\DateControl;

/* @var $this yii\web\View */
/* @var $model common\models\TenantLogbook */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Daftar Log Book Tenant
                    </h3>
                </div>
                <div class="panel-body" >
                    <div class="tenant-logbook-form">

                        <?php $form = ActiveForm::begin(); ?>
                        
                         <?php \Yii::$app->request->get('id_kegiatan') ? $model->id_kegiatan = \Yii::$app->request->get('id_kegiatan') : '' ?>
                        <?= $form->field($model, 'id_kegiatan')->hiddenInput()->label(false) ?>

                        <?php
                        // $form->field($model, 'id_kegiatan')->widget(Select2::classname(), [
                        //     'data' => ArrayHelper::map(TenantKegiatan::find()->isSelf()->orderBy('nama_kegiatan')->asArray()->all(), 'id', 'nama_kegiatan'),
                        //     'disabled' => true,
                        //     'options' => [
                        //         // 'disabled' => (! Yii::$app->user->can('Penelitian Pengajuan All')),
                        //         'placeholder' => 'Pilih Nama Nama Kegiatan ...',
                        //     ],
                        //     'pluginOptions' => [
                        //         'allowClear' => true,
                        //     ],
                        // ])
                        ?>
                        
                        <?= $form->field($model, 'jenis_belanja')->textInput(['maxlength' => true]) ?>

                        <?= $form->field($model, 'nominal')->textInput() ?>

                        <?php echo $form->field($model, 'tanggal_pengajuan')->widget(DateControl::classname(), [
                            'type'=>DateControl::FORMAT_DATE,
                            'ajaxConversion'=>false,
                            'widgetOptions' => [
                                'pluginOptions' => [
                                    'autoclose' => true
                                ]
                            ]
                        ]); ?>

                        <?php echo $form->field($model, 'tanggal_pencairan')->widget(DateControl::classname(), [
                            'type'=>DateControl::FORMAT_DATE,
                            'ajaxConversion'=>false,
                            'widgetOptions' => [
                                'pluginOptions' => [
                                    'autoclose' => true
                                ]
                            ]
                        ]); ?>

                        <div class="form-group">
                            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
                        </div>

                        <?php ActiveForm::end(); ?>

                    </div>
                </div>
                <div class="panel-footer">
                    Panel footer
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/tenant-logbook/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\TenantLogbookSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Daftar Log Book Tenant
                    </h3>
                </div>
                <div class="panel-body" >
                    <div class="tenant-logbook-search">

                        <?php $form = ActiveForm::begin([
                            'action' => ['index'],
                            'method' => 'get',
                        ]); ?>

                        <?= $form->field($model, 'id') ?>

                        <?= $form->field($model, 'id_kegiatan') ?>

                        <?= $form->field($model, 'jenis_belanja') ?>

                        <?= $form->field($model, 'nominal') ?>

                        <?= $form->field($model, 'tanggal_pengajuan') ?>

                        <?php // echo $form->field($model, 'tanggal_pencairan') ?>

                        <div class="form-group">
                            <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
                            <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
                        </div>

                        <?php ActiveForm::end(); ?>

                    </div>
                                    </div>
                <div class="panel-footer">
                    Panel footer
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/tenant-logbook/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\TenantLogbook */

$this->title = 'Create Tenant Logbook';
$this->params['breadcrumbs'][] = ['label' => 'Tenant Logbooks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tenant-logbook-create">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/tenant-logbook/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\TenantKegiatanSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tenant Log Book';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Daftar Log Book Tenant
                    </h3>
                </div>
                <div class="panel-body" >
                    <div class="tenant-kegiatan-index">
                        <?= GridView::widget([
                            'dataProvider' => $dataProvider,
                            'filterModel' => $searchModel,
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn'],

                                // 'id',
                                'nama_kegiatan',
                                'koordinator_peneliti',
                                // 'judul',
                                // 'tujuan:raw',
                                //'sasaran:raw',
                                //'id_pic',

                                [
                                    'buttons' => [
                                        'view' => function ($url, $model, $key) {
                                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', Url::to(['/tenant-logbook/logbook', 'TenantLogbookSearch[id_kegiatan]' => $model->id]), ['title' => Yii::t('yii', 'View')]);
                                        },
                                    ],
                                    'class' => 'yii\grid\ActionColumn',
                                    'template' => '{view}'
                                ],
                            ],
                        ]); ?>
                    </div>
                </div>
                <div class="panel-footer">
                    Panel footer
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/tenant-logbook/logbook.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\TenantLogbookSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tenant Logbooks';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Daftar Log Book Tenant
                    </h3>
                </div>
                <div class="panel-body" >
                    <div class="tenant-logbook-index">

                        <!-- <h1><?= Html::encode($this->title) ?></h1> -->
                        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

                        <p>
                            <?= Html::a('Create Tenant Logbook', ['create', 'id_kegiatan' => \Yii::$app->request->get('TenantLogbookSearch')['id_kegiatan']], ['class' => 'btn btn-success']) ?>
                        </p>

                        <?= GridView::widget([
                            'dataProvider' => $dataProvider,
                            'filterModel' => $searchModel,
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn'],

                                // 'id',
                                // 'id_kegiatan',
                                'jenis_belanja',
                                'nominal',
                                'tanggal_pengajuan',
                                //'tanggal_pencairan',

                                ['class' => 'yii\grid\ActionColumn'],
                            ],
                        ]); ?>
                    </div>
                </div>
                <div class="panel-footer">
                    Panel footer
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/tenant-logbook/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\TenantLogbook */

$this->title = 'Update Tenant Logbook';
$this->params['breadcrumbs'][] = ['label' => 'Tenant Logbooks', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tenant-logbook-update">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/tenant-logbook/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\TenantLogbook */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Tenant Logbooks', 'url' => ['logbook', 'TenantLogbookSearch[id_kegiatan]' => $model->id_kegiatan]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Daftar Log Book Tenant
                    </h3>
                </div>
                <div class="panel-body" >
                    <div class="tenant-logbook-view">

                        <h1><?= Html::encode($this->title) ?></h1>

                        <p>
                            <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                                'class' => 'btn btn-danger',
                                'data' => [
                                    'confirm' => 'Are you sure you want to delete this item?',
                                    'method' => 'post',
                                ],
                            ]) ?>
                        </p>

                        <?= DetailView::widget([
                            'model' => $model,
                            'attributes' => [
                                'id',
                                'id_kegiatan',
                                'jenis_belanja',
                                'nominal',
                                'tanggal_pengajuan',
                                'tanggal_pencairan',
                            ],
                        ]) ?>

                    </div>
                </div>
                <div class="panel-footer">
                    Panel footer
                </div>
            </div>
        </div>
    </div>
</div>